// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: archive.proto

#ifndef PROTOBUF_archive_2eproto__INCLUDED
#define PROTOBUF_archive_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3002000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3002000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
class ArchiveMemberProto;
class ArchiveMemberProtoDefaultTypeInternal;
extern ArchiveMemberProtoDefaultTypeInternal _ArchiveMemberProto_default_instance_;
class ArchiveProto;
class ArchiveProtoDefaultTypeInternal;
extern ArchiveProtoDefaultTypeInternal _ArchiveProto_default_instance_;
class AssociateProto;
class AssociateProtoDefaultTypeInternal;
extern AssociateProtoDefaultTypeInternal _AssociateProto_default_instance_;
class AssociateProto_ValueType;
class AssociateProto_ValueTypeDefaultTypeInternal;
extern AssociateProto_ValueTypeDefaultTypeInternal _AssociateProto_ValueType_default_instance_;
class FloatProto;
class FloatProtoDefaultTypeInternal;
extern FloatProtoDefaultTypeInternal _FloatProto_default_instance_;
class IntegerProto;
class IntegerProtoDefaultTypeInternal;
extern IntegerProtoDefaultTypeInternal _IntegerProto_default_instance_;
class SequenceProto;
class SequenceProtoDefaultTypeInternal;
extern SequenceProtoDefaultTypeInternal _SequenceProto_default_instance_;
class StringProto;
class StringProtoDefaultTypeInternal;
extern StringProtoDefaultTypeInternal _StringProto_default_instance_;

namespace protobuf_archive_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::uint32 offsets[];
  static void InitDefaultsImpl();
  static void Shutdown();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_archive_2eproto

// ===================================================================

class ArchiveProto : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ArchiveProto) */ {
 public:
  ArchiveProto();
  virtual ~ArchiveProto();

  ArchiveProto(const ArchiveProto& from);

  inline ArchiveProto& operator=(const ArchiveProto& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ArchiveProto& default_instance();

  static inline const ArchiveProto* internal_default_instance() {
    return reinterpret_cast<const ArchiveProto*>(
               &_ArchiveProto_default_instance_);
  }

  void Swap(ArchiveProto* other);

  // implements Message ----------------------------------------------

  inline ArchiveProto* New() const PROTOBUF_FINAL { return New(NULL); }

  ArchiveProto* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const ArchiveProto& from);
  void MergeFrom(const ArchiveProto& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(ArchiveProto* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .ArchiveMemberProto members = 1;
  int members_size() const;
  void clear_members();
  static const int kMembersFieldNumber = 1;
  const ::ArchiveMemberProto& members(int index) const;
  ::ArchiveMemberProto* mutable_members(int index);
  ::ArchiveMemberProto* add_members();
  ::google::protobuf::RepeatedPtrField< ::ArchiveMemberProto >*
      mutable_members();
  const ::google::protobuf::RepeatedPtrField< ::ArchiveMemberProto >&
      members() const;

  // @@protoc_insertion_point(class_scope:ArchiveProto)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::ArchiveMemberProto > members_;
  friend struct  protobuf_archive_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ArchiveMemberProto : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ArchiveMemberProto) */ {
 public:
  ArchiveMemberProto();
  virtual ~ArchiveMemberProto();

  ArchiveMemberProto(const ArchiveMemberProto& from);

  inline ArchiveMemberProto& operator=(const ArchiveMemberProto& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ArchiveMemberProto& default_instance();

  static inline const ArchiveMemberProto* internal_default_instance() {
    return reinterpret_cast<const ArchiveMemberProto*>(
               &_ArchiveMemberProto_default_instance_);
  }

  void Swap(ArchiveMemberProto* other);

  // implements Message ----------------------------------------------

  inline ArchiveMemberProto* New() const PROTOBUF_FINAL { return New(NULL); }

  ArchiveMemberProto* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const ArchiveMemberProto& from);
  void MergeFrom(const ArchiveMemberProto& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(ArchiveMemberProto* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional bytes data = 1;
  bool has_data() const;
  void clear_data();
  static const int kDataFieldNumber = 1;
  const ::std::string& data() const;
  void set_data(const ::std::string& value);
  #if LANG_CXX11
  void set_data(::std::string&& value);
  #endif
  void set_data(const char* value);
  void set_data(const void* value, size_t size);
  ::std::string* mutable_data();
  ::std::string* release_data();
  void set_allocated_data(::std::string* data);

  // @@protoc_insertion_point(class_scope:ArchiveMemberProto)
 private:
  void set_has_data();
  void clear_has_data();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr data_;
  friend struct  protobuf_archive_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class IntegerProto : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:IntegerProto) */ {
 public:
  IntegerProto();
  virtual ~IntegerProto();

  IntegerProto(const IntegerProto& from);

  inline IntegerProto& operator=(const IntegerProto& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const IntegerProto& default_instance();

  static inline const IntegerProto* internal_default_instance() {
    return reinterpret_cast<const IntegerProto*>(
               &_IntegerProto_default_instance_);
  }

  void Swap(IntegerProto* other);

  // implements Message ----------------------------------------------

  inline IntegerProto* New() const PROTOBUF_FINAL { return New(NULL); }

  IntegerProto* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const IntegerProto& from);
  void MergeFrom(const IntegerProto& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(IntegerProto* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint64 value = 1;
  bool has_value() const;
  void clear_value();
  static const int kValueFieldNumber = 1;
  ::google::protobuf::uint64 value() const;
  void set_value(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:IntegerProto)
 private:
  void set_has_value();
  void clear_has_value();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::uint64 value_;
  friend struct  protobuf_archive_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class FloatProto : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:FloatProto) */ {
 public:
  FloatProto();
  virtual ~FloatProto();

  FloatProto(const FloatProto& from);

  inline FloatProto& operator=(const FloatProto& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const FloatProto& default_instance();

  static inline const FloatProto* internal_default_instance() {
    return reinterpret_cast<const FloatProto*>(
               &_FloatProto_default_instance_);
  }

  void Swap(FloatProto* other);

  // implements Message ----------------------------------------------

  inline FloatProto* New() const PROTOBUF_FINAL { return New(NULL); }

  FloatProto* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const FloatProto& from);
  void MergeFrom(const FloatProto& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(FloatProto* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional double value = 1;
  bool has_value() const;
  void clear_value();
  static const int kValueFieldNumber = 1;
  double value() const;
  void set_value(double value);

  // @@protoc_insertion_point(class_scope:FloatProto)
 private:
  void set_has_value();
  void clear_has_value();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  double value_;
  friend struct  protobuf_archive_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class StringProto : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:StringProto) */ {
 public:
  StringProto();
  virtual ~StringProto();

  StringProto(const StringProto& from);

  inline StringProto& operator=(const StringProto& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const StringProto& default_instance();

  static inline const StringProto* internal_default_instance() {
    return reinterpret_cast<const StringProto*>(
               &_StringProto_default_instance_);
  }

  void Swap(StringProto* other);

  // implements Message ----------------------------------------------

  inline StringProto* New() const PROTOBUF_FINAL { return New(NULL); }

  StringProto* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const StringProto& from);
  void MergeFrom(const StringProto& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(StringProto* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string value = 1;
  bool has_value() const;
  void clear_value();
  static const int kValueFieldNumber = 1;
  const ::std::string& value() const;
  void set_value(const ::std::string& value);
  #if LANG_CXX11
  void set_value(::std::string&& value);
  #endif
  void set_value(const char* value);
  void set_value(const char* value, size_t size);
  ::std::string* mutable_value();
  ::std::string* release_value();
  void set_allocated_value(::std::string* value);

  // @@protoc_insertion_point(class_scope:StringProto)
 private:
  void set_has_value();
  void clear_has_value();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr value_;
  friend struct  protobuf_archive_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class SequenceProto : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:SequenceProto) */ {
 public:
  SequenceProto();
  virtual ~SequenceProto();

  SequenceProto(const SequenceProto& from);

  inline SequenceProto& operator=(const SequenceProto& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const SequenceProto& default_instance();

  static inline const SequenceProto* internal_default_instance() {
    return reinterpret_cast<const SequenceProto*>(
               &_SequenceProto_default_instance_);
  }

  void Swap(SequenceProto* other);

  // implements Message ----------------------------------------------

  inline SequenceProto* New() const PROTOBUF_FINAL { return New(NULL); }

  SequenceProto* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const SequenceProto& from);
  void MergeFrom(const SequenceProto& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(SequenceProto* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .ArchiveMemberProto values = 1;
  int values_size() const;
  void clear_values();
  static const int kValuesFieldNumber = 1;
  const ::ArchiveMemberProto& values(int index) const;
  ::ArchiveMemberProto* mutable_values(int index);
  ::ArchiveMemberProto* add_values();
  ::google::protobuf::RepeatedPtrField< ::ArchiveMemberProto >*
      mutable_values();
  const ::google::protobuf::RepeatedPtrField< ::ArchiveMemberProto >&
      values() const;

  // @@protoc_insertion_point(class_scope:SequenceProto)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::ArchiveMemberProto > values_;
  friend struct  protobuf_archive_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class AssociateProto_ValueType : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:AssociateProto.ValueType) */ {
 public:
  AssociateProto_ValueType();
  virtual ~AssociateProto_ValueType();

  AssociateProto_ValueType(const AssociateProto_ValueType& from);

  inline AssociateProto_ValueType& operator=(const AssociateProto_ValueType& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const AssociateProto_ValueType& default_instance();

  static inline const AssociateProto_ValueType* internal_default_instance() {
    return reinterpret_cast<const AssociateProto_ValueType*>(
               &_AssociateProto_ValueType_default_instance_);
  }

  void Swap(AssociateProto_ValueType* other);

  // implements Message ----------------------------------------------

  inline AssociateProto_ValueType* New() const PROTOBUF_FINAL { return New(NULL); }

  AssociateProto_ValueType* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const AssociateProto_ValueType& from);
  void MergeFrom(const AssociateProto_ValueType& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(AssociateProto_ValueType* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .ArchiveMemberProto key = 1;
  bool has_key() const;
  void clear_key();
  static const int kKeyFieldNumber = 1;
  const ::ArchiveMemberProto& key() const;
  ::ArchiveMemberProto* mutable_key();
  ::ArchiveMemberProto* release_key();
  void set_allocated_key(::ArchiveMemberProto* key);

  // optional .ArchiveMemberProto value = 2;
  bool has_value() const;
  void clear_value();
  static const int kValueFieldNumber = 2;
  const ::ArchiveMemberProto& value() const;
  ::ArchiveMemberProto* mutable_value();
  ::ArchiveMemberProto* release_value();
  void set_allocated_value(::ArchiveMemberProto* value);

  // @@protoc_insertion_point(class_scope:AssociateProto.ValueType)
 private:
  void set_has_key();
  void clear_has_key();
  void set_has_value();
  void clear_has_value();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::ArchiveMemberProto* key_;
  ::ArchiveMemberProto* value_;
  friend struct  protobuf_archive_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class AssociateProto : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:AssociateProto) */ {
 public:
  AssociateProto();
  virtual ~AssociateProto();

  AssociateProto(const AssociateProto& from);

  inline AssociateProto& operator=(const AssociateProto& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const AssociateProto& default_instance();

  static inline const AssociateProto* internal_default_instance() {
    return reinterpret_cast<const AssociateProto*>(
               &_AssociateProto_default_instance_);
  }

  void Swap(AssociateProto* other);

  // implements Message ----------------------------------------------

  inline AssociateProto* New() const PROTOBUF_FINAL { return New(NULL); }

  AssociateProto* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const AssociateProto& from);
  void MergeFrom(const AssociateProto& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(AssociateProto* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  typedef AssociateProto_ValueType ValueType;

  // accessors -------------------------------------------------------

  // repeated .AssociateProto.ValueType values = 1;
  int values_size() const;
  void clear_values();
  static const int kValuesFieldNumber = 1;
  const ::AssociateProto_ValueType& values(int index) const;
  ::AssociateProto_ValueType* mutable_values(int index);
  ::AssociateProto_ValueType* add_values();
  ::google::protobuf::RepeatedPtrField< ::AssociateProto_ValueType >*
      mutable_values();
  const ::google::protobuf::RepeatedPtrField< ::AssociateProto_ValueType >&
      values() const;

  // @@protoc_insertion_point(class_scope:AssociateProto)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::AssociateProto_ValueType > values_;
  friend struct  protobuf_archive_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// ArchiveProto

// repeated .ArchiveMemberProto members = 1;
inline int ArchiveProto::members_size() const {
  return members_.size();
}
inline void ArchiveProto::clear_members() {
  members_.Clear();
}
inline const ::ArchiveMemberProto& ArchiveProto::members(int index) const {
  // @@protoc_insertion_point(field_get:ArchiveProto.members)
  return members_.Get(index);
}
inline ::ArchiveMemberProto* ArchiveProto::mutable_members(int index) {
  // @@protoc_insertion_point(field_mutable:ArchiveProto.members)
  return members_.Mutable(index);
}
inline ::ArchiveMemberProto* ArchiveProto::add_members() {
  // @@protoc_insertion_point(field_add:ArchiveProto.members)
  return members_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::ArchiveMemberProto >*
ArchiveProto::mutable_members() {
  // @@protoc_insertion_point(field_mutable_list:ArchiveProto.members)
  return &members_;
}
inline const ::google::protobuf::RepeatedPtrField< ::ArchiveMemberProto >&
ArchiveProto::members() const {
  // @@protoc_insertion_point(field_list:ArchiveProto.members)
  return members_;
}

// -------------------------------------------------------------------

// ArchiveMemberProto

// optional bytes data = 1;
inline bool ArchiveMemberProto::has_data() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ArchiveMemberProto::set_has_data() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ArchiveMemberProto::clear_has_data() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ArchiveMemberProto::clear_data() {
  data_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_data();
}
inline const ::std::string& ArchiveMemberProto::data() const {
  // @@protoc_insertion_point(field_get:ArchiveMemberProto.data)
  return data_.GetNoArena();
}
inline void ArchiveMemberProto::set_data(const ::std::string& value) {
  set_has_data();
  data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:ArchiveMemberProto.data)
}
#if LANG_CXX11
inline void ArchiveMemberProto::set_data(::std::string&& value) {
  set_has_data();
  data_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:ArchiveMemberProto.data)
}
#endif
inline void ArchiveMemberProto::set_data(const char* value) {
  set_has_data();
  data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:ArchiveMemberProto.data)
}
inline void ArchiveMemberProto::set_data(const void* value, size_t size) {
  set_has_data();
  data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:ArchiveMemberProto.data)
}
inline ::std::string* ArchiveMemberProto::mutable_data() {
  set_has_data();
  // @@protoc_insertion_point(field_mutable:ArchiveMemberProto.data)
  return data_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ArchiveMemberProto::release_data() {
  // @@protoc_insertion_point(field_release:ArchiveMemberProto.data)
  clear_has_data();
  return data_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ArchiveMemberProto::set_allocated_data(::std::string* data) {
  if (data != NULL) {
    set_has_data();
  } else {
    clear_has_data();
  }
  data_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), data);
  // @@protoc_insertion_point(field_set_allocated:ArchiveMemberProto.data)
}

// -------------------------------------------------------------------

// IntegerProto

// optional uint64 value = 1;
inline bool IntegerProto::has_value() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void IntegerProto::set_has_value() {
  _has_bits_[0] |= 0x00000001u;
}
inline void IntegerProto::clear_has_value() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void IntegerProto::clear_value() {
  value_ = GOOGLE_ULONGLONG(0);
  clear_has_value();
}
inline ::google::protobuf::uint64 IntegerProto::value() const {
  // @@protoc_insertion_point(field_get:IntegerProto.value)
  return value_;
}
inline void IntegerProto::set_value(::google::protobuf::uint64 value) {
  set_has_value();
  value_ = value;
  // @@protoc_insertion_point(field_set:IntegerProto.value)
}

// -------------------------------------------------------------------

// FloatProto

// optional double value = 1;
inline bool FloatProto::has_value() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void FloatProto::set_has_value() {
  _has_bits_[0] |= 0x00000001u;
}
inline void FloatProto::clear_has_value() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void FloatProto::clear_value() {
  value_ = 0;
  clear_has_value();
}
inline double FloatProto::value() const {
  // @@protoc_insertion_point(field_get:FloatProto.value)
  return value_;
}
inline void FloatProto::set_value(double value) {
  set_has_value();
  value_ = value;
  // @@protoc_insertion_point(field_set:FloatProto.value)
}

// -------------------------------------------------------------------

// StringProto

// optional string value = 1;
inline bool StringProto::has_value() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void StringProto::set_has_value() {
  _has_bits_[0] |= 0x00000001u;
}
inline void StringProto::clear_has_value() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void StringProto::clear_value() {
  value_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_value();
}
inline const ::std::string& StringProto::value() const {
  // @@protoc_insertion_point(field_get:StringProto.value)
  return value_.GetNoArena();
}
inline void StringProto::set_value(const ::std::string& value) {
  set_has_value();
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:StringProto.value)
}
#if LANG_CXX11
inline void StringProto::set_value(::std::string&& value) {
  set_has_value();
  value_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:StringProto.value)
}
#endif
inline void StringProto::set_value(const char* value) {
  set_has_value();
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:StringProto.value)
}
inline void StringProto::set_value(const char* value, size_t size) {
  set_has_value();
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:StringProto.value)
}
inline ::std::string* StringProto::mutable_value() {
  set_has_value();
  // @@protoc_insertion_point(field_mutable:StringProto.value)
  return value_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* StringProto::release_value() {
  // @@protoc_insertion_point(field_release:StringProto.value)
  clear_has_value();
  return value_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void StringProto::set_allocated_value(::std::string* value) {
  if (value != NULL) {
    set_has_value();
  } else {
    clear_has_value();
  }
  value_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set_allocated:StringProto.value)
}

// -------------------------------------------------------------------

// SequenceProto

// repeated .ArchiveMemberProto values = 1;
inline int SequenceProto::values_size() const {
  return values_.size();
}
inline void SequenceProto::clear_values() {
  values_.Clear();
}
inline const ::ArchiveMemberProto& SequenceProto::values(int index) const {
  // @@protoc_insertion_point(field_get:SequenceProto.values)
  return values_.Get(index);
}
inline ::ArchiveMemberProto* SequenceProto::mutable_values(int index) {
  // @@protoc_insertion_point(field_mutable:SequenceProto.values)
  return values_.Mutable(index);
}
inline ::ArchiveMemberProto* SequenceProto::add_values() {
  // @@protoc_insertion_point(field_add:SequenceProto.values)
  return values_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::ArchiveMemberProto >*
SequenceProto::mutable_values() {
  // @@protoc_insertion_point(field_mutable_list:SequenceProto.values)
  return &values_;
}
inline const ::google::protobuf::RepeatedPtrField< ::ArchiveMemberProto >&
SequenceProto::values() const {
  // @@protoc_insertion_point(field_list:SequenceProto.values)
  return values_;
}

// -------------------------------------------------------------------

// AssociateProto_ValueType

// optional .ArchiveMemberProto key = 1;
inline bool AssociateProto_ValueType::has_key() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void AssociateProto_ValueType::set_has_key() {
  _has_bits_[0] |= 0x00000001u;
}
inline void AssociateProto_ValueType::clear_has_key() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void AssociateProto_ValueType::clear_key() {
  if (key_ != NULL) key_->::ArchiveMemberProto::Clear();
  clear_has_key();
}
inline const ::ArchiveMemberProto& AssociateProto_ValueType::key() const {
  // @@protoc_insertion_point(field_get:AssociateProto.ValueType.key)
  return key_ != NULL ? *key_
                         : *::ArchiveMemberProto::internal_default_instance();
}
inline ::ArchiveMemberProto* AssociateProto_ValueType::mutable_key() {
  set_has_key();
  if (key_ == NULL) {
    key_ = new ::ArchiveMemberProto;
  }
  // @@protoc_insertion_point(field_mutable:AssociateProto.ValueType.key)
  return key_;
}
inline ::ArchiveMemberProto* AssociateProto_ValueType::release_key() {
  // @@protoc_insertion_point(field_release:AssociateProto.ValueType.key)
  clear_has_key();
  ::ArchiveMemberProto* temp = key_;
  key_ = NULL;
  return temp;
}
inline void AssociateProto_ValueType::set_allocated_key(::ArchiveMemberProto* key) {
  delete key_;
  key_ = key;
  if (key) {
    set_has_key();
  } else {
    clear_has_key();
  }
  // @@protoc_insertion_point(field_set_allocated:AssociateProto.ValueType.key)
}

// optional .ArchiveMemberProto value = 2;
inline bool AssociateProto_ValueType::has_value() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void AssociateProto_ValueType::set_has_value() {
  _has_bits_[0] |= 0x00000002u;
}
inline void AssociateProto_ValueType::clear_has_value() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void AssociateProto_ValueType::clear_value() {
  if (value_ != NULL) value_->::ArchiveMemberProto::Clear();
  clear_has_value();
}
inline const ::ArchiveMemberProto& AssociateProto_ValueType::value() const {
  // @@protoc_insertion_point(field_get:AssociateProto.ValueType.value)
  return value_ != NULL ? *value_
                         : *::ArchiveMemberProto::internal_default_instance();
}
inline ::ArchiveMemberProto* AssociateProto_ValueType::mutable_value() {
  set_has_value();
  if (value_ == NULL) {
    value_ = new ::ArchiveMemberProto;
  }
  // @@protoc_insertion_point(field_mutable:AssociateProto.ValueType.value)
  return value_;
}
inline ::ArchiveMemberProto* AssociateProto_ValueType::release_value() {
  // @@protoc_insertion_point(field_release:AssociateProto.ValueType.value)
  clear_has_value();
  ::ArchiveMemberProto* temp = value_;
  value_ = NULL;
  return temp;
}
inline void AssociateProto_ValueType::set_allocated_value(::ArchiveMemberProto* value) {
  delete value_;
  value_ = value;
  if (value) {
    set_has_value();
  } else {
    clear_has_value();
  }
  // @@protoc_insertion_point(field_set_allocated:AssociateProto.ValueType.value)
}

// -------------------------------------------------------------------

// AssociateProto

// repeated .AssociateProto.ValueType values = 1;
inline int AssociateProto::values_size() const {
  return values_.size();
}
inline void AssociateProto::clear_values() {
  values_.Clear();
}
inline const ::AssociateProto_ValueType& AssociateProto::values(int index) const {
  // @@protoc_insertion_point(field_get:AssociateProto.values)
  return values_.Get(index);
}
inline ::AssociateProto_ValueType* AssociateProto::mutable_values(int index) {
  // @@protoc_insertion_point(field_mutable:AssociateProto.values)
  return values_.Mutable(index);
}
inline ::AssociateProto_ValueType* AssociateProto::add_values() {
  // @@protoc_insertion_point(field_add:AssociateProto.values)
  return values_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::AssociateProto_ValueType >*
AssociateProto::mutable_values() {
  // @@protoc_insertion_point(field_mutable_list:AssociateProto.values)
  return &values_;
}
inline const ::google::protobuf::RepeatedPtrField< ::AssociateProto_ValueType >&
AssociateProto::values() const {
  // @@protoc_insertion_point(field_list:AssociateProto.values)
  return values_;
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_archive_2eproto__INCLUDED
